project:
  type: book

book:
  title: "Computational Reproducibility"
  author: "Jürgen Schneider"
  date: "18.12.2024"
  chapters:
    - index.qmd
    - 41_solutions_fileformat.qmd
    - 42_solutions_inputoutput.qmd
    - 43_solutions_version.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
css: www/style.css


