\
\

Here you'll find information on how to make your data analyses computational reproducibile.


## General {.unnumbered}

* Basic requirement: **Share** data and analyses (see [`closed_data()` function from WORCS](https://cjvanlissa.github.io/worcs/) or [synthpop package](https://www.synthpop.org.uk/get-started.html) in case you can't share data)
* Set up your work as a **'project'**, where all related files (e.g., data, scripts, results) are stored together in a single folder (as with R-projects) or in a single file (as with JASP and jamovi). Avoid working with isolated files, and use **relative paths** to connect files within the project.
* Use a clear folder structure and readme files

The [Workflow for Open Reproducible Code in Science (WORCS)](https://doi.org/10.3233/DS-210031) is an excellent framework that also integrates recommendations we give here.





## Contents {.unnumbered}
See also navigation menu on the left.

<a href="41_solutions_fileformat.qmd" class="infobtn btn-index"><mark><b>Open file formats and software</b><br />Ensuring cost-free access to your analyses</mark></a>
<a href="42_solutions_inputoutput.qmd" class="infobtn btn-index"><mark><b>Input-output-documents</b><br />Making analyses comprehensible for yourself and others</mark></a>
<a href="43_solutions_version.qmd" class="infobtn btn-index"><mark><b>Containerization and version management</b><br />Making analyses system-independent and sustainable</mark></a>